export const STORE_GLOBAL_CODES = "STORE_GLOBAL_CODES";
export const STORE_BUSSINESS_DETAIL = "STORE_BUSSINESS_DETAIL";
export const STORE_LOCATION_SELECTED = "STORE_LOCATION_SELECTED";
export const STORE_INVENTORY_DETAIL = "STORE_INVENTORY_DETAIL";
export const STORE_ADDITEM_ID = "STORE_ADDITEM_ID";
export const STORE_ADDACTIVITY_ID = "STORE_ADDACTIVITY_ID";